# -*- mode: ruby -*-
# vi: set ft=ruby :

#

require 'yaml'

# Load  conf.yml.
config_data = begin
  puts "conf.yml parsing ..."
  YAML.load_file('conf.yml')
  rescue
    STDERR.puts "conf.yml could not be loaded."
    exit
end

# Verify conf_data values
puts config_data.inspect

# Vagrantfile 
Vagrant.configure("2") do |config|
  # Box
  config.vm.box = config_data["vagrant_box"]

  # Network
  config.vm.network "private_network", ip: config_data["ip_address"]
  config.vm.network  "forwarded_port", guest: 8000, host: 8000

  # Shared folders
  config.vm.synced_folder "django-projects", "/home/vagrant/django-projects"

  # Provisioning
  config.vm.provision "shell", path: "provisioning/provision-linux.sh" , privileged: false
  config.vm.provision "shell", path: "provisioning/provision-python.sh", privileged: false, args: config_data["python_version"].to_s
  config.vm.provision "shell", path: "provisioning/provision-django.sh", privileged: false, args: config_data["python_version"].to_s + " " + config_data["django_version"] + " " + config_data["project_name"]
end
